version: "3.9"

services:

  lyxa-api-gateway:
    build:
      context: ./lyxa-api-gateway
      dockerfile: Dockerfile
    container_name: lyxa-api-gateway
    ports:
      - "5001:5001"
    env_file:
      - ./lyxa-api-gateway/.env
    depends_on:
      - lyxa-auth-service
      - lyxa-product-service
      - rabbitmq
      - mongodb
    networks:
      - lyxa-network
    entrypoint: ["sh", "-c", "sleep 20 && node dist/main.js"]

  lyxa-auth-service:
    build:
      context: ./lyxa-auth-service
      dockerfile: Dockerfile
    container_name: lyxa-auth-service
    ports:
      - "50051:50051"
    env_file:
      - ./lyxa-auth-service/.env
    depends_on:
      - rabbitmq
      - mongodb
    networks:
      - lyxa-network
    entrypoint: ["sh", "-c", "sleep 10 && node dist/main.js"]

  lyxa-product-service:
    build:
      context: ./lyxa-product-service
      dockerfile: Dockerfile
    container_name: lyxa-product-service
    ports:
      - "50053:50053"
    env_file:
      - ./lyxa-product-service/.env
    depends_on:
      - rabbitmq
      - mongodb
    networks:
      - lyxa-network
    entrypoint: ["sh", "-c", "sleep 10 && node dist/main.js"]
  
  mongodb:
    image: mongo:8.2.6-rc0-noble
    container_name: lyxa-mongodb
    restart: unless-stopped
    ports:
      - "29017:27017"
    volumes:
      - lyxa_mongodb_data:/data/db
    networks:
      - lyxa-network

  rabbitmq:
    image: rabbitmq:4-management
    container_name: lyxa-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: lyxa_user
      RABBITMQ_DEFAULT_PASS: lyxa_password
    volumes:
      - lyxa_rabbitmq_data:/var/lib/rabbitmq
    networks:
      - lyxa-network

volumes:
  lyxa_mongodb_data:
  lyxa_rabbitmq_data:

networks:
  lyxa-network:
    driver: bridge
